### ISSUE TITLE
1페이지 클릭 시 메인으로 갑니다.

### ISSUE THREAD

**Issue by djm03178** [infossm/infossm.github.io#19]
https://infossm.github.io/blog/page/2/ 에서 하단의 1을 누르면 1페이지로 가지 않고 https://infossm.github.io/ 로 넘어갑니다.

**Comment by KENNYSOFT** [comment]
https://github.com/infossm/infossm.github.io/commit/7778d63bdd24ae20279fb28bb10178fd3867de7d 에서 해결되었습니다.
