### ISSUE TITLE
Markdown에서 bold가 작동하지 않습니다.

### ISSUE THREAD

**Issue by evenharder** [infossm/infossm.github.io#24]
https://infossm.github.io/blog/2018/10/01/md-test/ 의 Emphasis 문단만 봐도 bold text가 bold가 아닙니다.

![markdown-bold-not-working](https://user-images.githubusercontent.com/12812402/50969115-aa313880-1520-11e9-9d8b-dffa9010d44c.png)

**Comment by KENNYSOFT** [comment]
[screen.css L43-L45](https://github.com/infossm/infossm.github.io/blob/master/assets/css/screen.css#L43-45)
```css
b, strong, optgroup {
    font-weight: 400;
}
```

400을 600 정도로 바꾸면 해결됩니다.

![image](https://user-images.githubusercontent.com/6624567/50990393-407f5180-1555-11e9-9b68-ddf5f0201604.png)

**Comment by orange4glace** [comment]
fixed in #31. need closing.

**Comment by KENNYSOFT** [comment]
팁: PR 제목을 `Fix #24`나 `Resolve #24` 등으로 적으면 Merge될 때 자동으로 함께 닫힙니다.

**Comment by orange4glace** [comment]
Fix #24. Merged into #31

**Comment by orange4glace** [comment]
@KENNYSOFT collaborator 가 아니라서 안되는것 같아욤

**Comment by KENNYSOFT** [comment]
여기 댓글이 아니고 Pull Request의 제목에 쓰셔야 합니다.

**Comment by KENNYSOFT** [comment]
음 제목은 아니고 커밋 이름으로 해야 하는 것 같습니다
