### ISSUE TITLE
[2019-06-16-python-biginteger.md] 링크 깨짐

### ISSUE THREAD

**Issue by Sait2000** [infossm/infossm.github.io#674]
https://github.com/infossm/infossm.github.io/blob/e68d5c13a291aebd74e4a6dee47dbe87e209a01f/_posts/2019-06-16-python-biginteger.md?plain=1#L18

링크가 깨져있습니다. 맨 처음 링크만 확인해봤는데 https://github.com/python/cpython/blob/main/Include/cpython/longintrepr.h 로 옮겨간 것 같습니다.

링크를 새 주소로 업데이트하거나 permalink로 하는 편이 좋을 것 같습니다.

@djm03178 확인 부탁드립니다

**Comment by djm03178** [comment]
#675 수정했습니다.
